name: ActivityPub - Sync

on:
  workflow_dispatch:
  schedule: [ { cron: '20 4 * * *' } ]

permissions: { contents: write }

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Sync data
        working-directory: src/activitypub
        run: bun run sync.ts
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ActivityPub - Sync - ${{ github.event.repository.updated_at }}
          directory: data/activitypub
