name: Links

on:
  workflow_dispatch:
  schedule: [ { cron: '45 23 * * *' } ]

permissions: { contents: write }

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Repair data
        working-directory: src
        run: deno run --allow-all repair.ts
      - name: Update links
        working-directory: src
        run: deno run --allow-all links.ts
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Links - ${{ github.event.repository.updated_at }}
          directory: data
